name: actualiza_libro

# Ejecutar cuando se realiza un cambio en main o a determinadas horas
on:
  push:
    branches:
    - main
# Para actualizar periódicamente desde las 11:30 hrs. hasta las 19:30 hrs. (hora en Chile)
  schedule:
    - cron: "30 15-23 * * *"

# Ejecutamos Jupyter Books, push a main y luego a gh-pages
jobs:
  actualiza_libro:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 
        fetch-depth: 0 
    
    # Para correcto formateado en español (ubuntu)
    - name: Instalando paquete español
      run: |
        sudo apt-get update
        sudo apt-get install language-pack-es
    
    # Python 3.7
    - name: Inicializando Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    # Instalando dependencias
    - name: Instalando dependencias de Python
      run: |
        pip install -r requirements.txt
    # Jupyter Book
    - name: Procesando libro
      run: |
        jupyter-book build .

    - name: Commit
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Add changes" -a
    - name: Actualizando main
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        
    # Push a gh-pages
    - name: Actualizando gh-pages
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
